[env:esp32doit-devkit-v1]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/54.03.20/platform-espressif32.zip
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
board_build.partitions = default.csv
board_build.filesystem = littlefs

; Optional build flags you can tweak as needed
build_flags = -Wno-error=cast-qual

lib_deps =
  mathertel/OneButton @ ^2.5.0
  RobTillaart/RunningMedian
  plerup/espsoftwareserial
  mikalhart/TinyGPSPlus
    
  me-no-dev/ESPAsyncWebServer
  bblanchon/ArduinoJson
  me-no-dev/AsyncTCP